apiVersion: v1
kind: Namespace
metadata:
  name: shopsphere
  labels:
    app.kubernetes.io/name: shopsphere
    environment: production
    # 'baseline' — 'restricted' blocks the official postgres image
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
