pipeline {
    agent any

    environment {
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    options {
        timestamps()
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Backend Test') {
            steps {
                dir('app/backend') {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }

        stage('Frontend Test') {
            steps {
                dir('app/frontend') {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }

        stage('Trivy FS Scan') {
            steps {
                sh 'trivy fs --severity HIGH,CRITICAL --no-progress . || true'
            }
        }

        stage('Build Backend') {
            steps {
                sh "docker build -t shopsphere/backend:${IMAGE_TAG} -f docker/backend/Dockerfile ."
            }
        }

        stage('Build Frontend') {
            steps {
                sh "docker build -t shopsphere/frontend:${IMAGE_TAG} -f docker/frontend/Dockerfile ."
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh "trivy image --severity HIGH,CRITICAL --no-progress shopsphere/backend:${IMAGE_TAG}  || true"
                sh "trivy image --severity HIGH,CRITICAL --no-progress shopsphere/frontend:${IMAGE_TAG} || true"
            }
        }

        stage('Push') {
            steps {
                echo "Push shopsphere/backend:${IMAGE_TAG}  and shopsphere/frontend:${IMAGE_TAG} to your registry (ECR/DockerHub)."
            }
        }

        stage('Update GitOps Repo') {
            steps {
                echo "In production: clone gitops repo, bump image tag, commit, push."
                echo "Argo CD then reconciles."
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
