apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shopsphere
  labels:
    app: shopsphere-backend
spec:
  selector:
    app: shopsphere-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
