apiVersion: v1
kind: ConfigMap
metadata:
  name: shopsphere-config
  namespace: shopsphere
data:
  APP_NAME: "ShopSphere"
  APP_ENV: "production"
  LOG_LEVEL: "info"
  BACKEND_PORT: "8080"
  BACKEND_URL: "http://backend:8080"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "shopsphere"
